#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GlassViewDroid.Demo.Resource", IsApplication=true)]

namespace GlassViewDroid.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GlassViewDroid.Resource.Attribute.BlurRadius = global::GlassViewDroid.Demo.Resource.Attribute.BlurRadius;
			global::GlassViewDroid.Resource.Attribute.DownSampling = global::GlassViewDroid.Demo.Resource.Attribute.DownSampling;
			global::GlassViewDroid.Resource.Styleable.GlassView = global::GlassViewDroid.Demo.Resource.Styleable.GlassView;
			global::GlassViewDroid.Resource.Styleable.GlassView_BlurRadius = global::GlassViewDroid.Demo.Resource.Styleable.GlassView_BlurRadius;
			global::GlassViewDroid.Resource.Styleable.GlassView_DownSampling = global::GlassViewDroid.Demo.Resource.Styleable.GlassView_DownSampling;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int BlurRadius = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int DownSampling = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int LolipopBg = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int BgImg = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int BottomGlassView = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int PromptTxt = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SeekBar = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int TopGlassView = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainActivity = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] GlassView = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int GlassView_BlurRadius = 1;
			
			// aapt resource value: 0
			public const int GlassView_DownSampling = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
